### ISSUE TITLE
Empty Data Directories Producing Errors

### ISSUE THREAD

**Issue by jyoung22** [whole-tale/whole-tale#36] opened 2018-08-23 18:56 UTC
When I try to launch Tales, the data directory shows up blank and when I try to view inside the data folder on R or Python, I get errors saying 

> "Error navigating to ~/work/data: Bad address"

 for R and 

> "Server error: Traceback (most recent call last): File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute result = yield result File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run value = future.result() File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model for name in os.listdir(os_dir): OSError: [Errno 14] Bad address: '/home/jovyan/work/data'"

for Python. 

I don't think it's a problem with the data not being uploaded though since I know that at least one of these Tales shows the data files and coding files when viewed by someone else.

**Comment by ThomasThelen** [comment] 2018-08-23 19:05
Thanks for letting us know about this issue; it looks related to [this issue](https://github.com/whole-tale/dashboard/issues/39) and it looks like [we have a fix](https://github.com/whole-tale/girder_wholetale/commit/0a43694b1c0dace1b1858b9f26d9f4b7f1484ad0). @craig-willis it looks like that PR was done after the 0.4 release, which means it probably isn't in production yet.

**Comment by craig-willis** [comment] 2018-08-24 14:05
Thank you @jallie58.  It would be very helpful if you could provide a step-by-step of what you did so I can reproduce the error.  For example:
* Registered or uploaded dataset. If registered, provide the URL or DOI
* Composed tale by selecting dataset or specific files

**Comment by Xarthisius** [comment] 2018-08-25 10:11
It was Tale: "Machine Learning: An Applied Econometric Approach" (id: 5b7ee5d94145320001601434). It's currently public, but it's mountpoint (folderId: 5b7ee5d94145320001601434) is owned by someone else and currently private.

It's fixed by https://github.com/whole-tale/girder_wholetale/pull/124 but it wasn't released yet.

**Comment by ThomasThelen** [comment] 2019-09-09 18:33
Fixed (See above)

**Closed by ThomasThelen** 2019-09-09 18:33 UTC
